### ISSUE TITLE
Youtube Downloader - Progress Tracking

### ISSUE THREAD

**Issue by dselmanovic** [Joystream/youtube-synch#11]
# Architecture documentation
- [x] Create an overall systems architecture specs
- [x] Confirm architecture

# AWS Environment
- [x] Get access to AWS
  Done partially as not all permissions are given
- [ ] Setup staging DB
- [ ] Setup staging Lambdas
- [ ] Setup staging Docker Orchestration

# Database
- [x] Create local DB structure
- [x] Create staging DB structure
- [x] Create DB API service
- [ ] Convert API service to AWS Lambda

# Monitor service
- [x] Setup ORM and DB API
- [ ] Service authentication and security
- [x] Youtube API wrapper
- [ ] Monitor service implementation

# Initiator service
- [x] Setup ORM and DB API
- [ ] Service authentication and security
- [ ] Docker Orchestration API wrapper
- [ ] Initiator service implementation

# Downloader service
- [x] Setup ORM and DB API
- [x] Service authentication and security
- [x] Downloader service implementation
- [ ] Deploy the service 

# Infrastructure
- [ ] Setup logging
- [ ] Setup CI/CD deployment pipeline
- [ ] Write Unit tests
- [ ] Write Integration tests
- [ ] Documentation of the system

# Integration to other systems
TBD
